cors:
  originPatterns: http://localhost:8080,http://localhost:3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_marcon?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    # properties:
     # hibernate:
      #  dialect: org.hibernate.dialect.MySQLDialect
      show-sql: false
springdoc:
  pathsToMatch: /pearson/** , /book/**
  swagger-ui:
    use-root-path: true
  
      
